# Generated by Django 5.0 on 2025-03-09 13:41

import accounts.models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetPassword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username_email", models.CharField(max_length=100, unique=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, unique=True
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birthday", models.DateField(verbose_name="birthday")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("is_conformed", models.BooleanField(default=False)),
                ("conform_code", models.CharField(editable=False, max_length=7)),
                ("first_ip", models.GenericIPAddressField(editable=False, null=True)),
                ("ip", models.GenericIPAddressField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.save_picture,
                        verbose_name="user picture",
                    ),
                ),
                (
                    "photo_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.save_icon,
                        verbose_name="user picture icon",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birthday", models.DateField(verbose_name="birthday")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("is_conformed", models.BooleanField(default=False)),
                ("conform_code", models.CharField(editable=False, max_length=7)),
                ("first_ip", models.GenericIPAddressField(editable=False, null=True)),
                ("ip", models.GenericIPAddressField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.save_picture,
                        verbose_name="user picture",
                    ),
                ),
                (
                    "photo_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.save_icon,
                        verbose_name="user picture icon",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Family name", max_length=100)),
                ("about", models.CharField(blank=True, max_length=255)),
                (
                    "family_status",
                    models.CharField(
                        choices=[
                            ("M", "Married"),
                            ("D", "Divorced"),
                            ("S", "Single"),
                            ("W", "Widowed"),
                        ],
                        default="M",
                        help_text="relational status of the family",
                        max_length=1,
                    ),
                ),
                (
                    "creater",
                    models.CharField(
                        choices=[("F", "Father"), ("M", "Mother")], max_length=1
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default/family.png",
                        null=True,
                        upload_to=accounts.models.save_picture,
                        verbose_name="Family picture",
                    ),
                ),
                (
                    "photo_icon",
                    models.ImageField(
                        blank=True,
                        default="default/family.png",
                        null=True,
                        upload_to=accounts.models.save_icon,
                        verbose_name="Family profil picture icon",
                    ),
                ),
                ("kids", models.ManyToManyField(blank=True, to="accounts.child")),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="father",
                        to="accounts.parent",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mother",
                        to="accounts.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family",
                "verbose_name_plural": "Families",
            },
        ),
    ]
