# Generated by Django 5.0 on 2025-03-10 15:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="qr_code",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parent",
            name="qr_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.save_qr,
                verbose_name="parent qr",
            ),
        ),
    ]
