# Generated by Django 5.0 on 2025-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_parent_qr_code_parent_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="qr_code",
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
