# Generated by Django 5.0 on 2025-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_family_qr_code_family_qr_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="last_updated",
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="code",
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="family",
            unique_together={("father", "mother")},
        ),
    ]
