# Generated by Django 5.0 on 2025-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_remove_child_last_updated_remove_parent_last_updated_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="child",
            old_name="is_conformed",
            new_name="is_confirmed",
        ),
        migrations.RenameField(
            model_name="parent",
            old_name="is_conformed",
            new_name="is_confirmed",
        ),
    ]
