# Generated by Django 5.0 on 2025-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_is_conformed_child_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="passlock",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
