# Generated by Django 5.0 on 2025-04-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_child_passlock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="passlock",
        ),
        migrations.AddField(
            model_name="child",
            name="passkey",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
