# Generated by Django 5.0 on 2025-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_child_passlock_child_passkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="passkey",
        ),
    ]
