# Generated by Django 5.0 on 2025-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_child_passkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="phone_locked",
            field=models.BooleanField(default=True),
        ),
    ]
