# Generated by Django 5.0 on 2025-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_child_phone_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="last_seen",
        ),
        migrations.RemoveField(
            model_name="family",
            name="creater",
        ),
        migrations.RemoveField(
            model_name="family",
            name="family_status",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="last_seen",
        ),
        migrations.AddField(
            model_name="child",
            name="whatsapp2_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="child",
            name="whatsapp_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
