# Generated by Django 5.0 on 2025-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_child_last_seen_remove_family_creater_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="photo_icon",
        ),
        migrations.RemoveField(
            model_name="family",
            name="photo_icon",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="photo_icon",
        ),
    ]
