# Generated by Django 5.0 on 2025-05-13 21:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_child_photo_icon_remove_family_photo_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="qr_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.save_qr,
                verbose_name="Family qr",
            ),
        ),
    ]
