# Generated by Django 5.0 on 2025-05-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_family_qr_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="conform_code",
        ),
        migrations.RemoveField(
            model_name="child",
            name="is_confirmed",
        ),
        migrations.RemoveField(
            model_name="child",
            name="whatsapp2_name",
        ),
        migrations.RemoveField(
            model_name="child",
            name="whatsapp_name",
        ),
    ]
