# Generated by Django 5.0 on 2025-06-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_remove_child_conform_code_remove_child_is_confirmed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
