# Generated by Django 5.0 on 2025-06-24 17:58

import control.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0015_alter_family_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.IntegerField()),
                ("usage_seconds", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["hour"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("alert", "Alert"),
                            ("reminder", "Reminder"),
                            ("info", "Information"),
                            ("warning", "Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ChildBadWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bad_words", models.ManyToManyField(blank=True, to="control.badword")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_bad_words",
                        to="accounts.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildCallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Device timestamp of the call"),
                ),
                (
                    "record_file",
                    models.FileField(upload_to=control.models.child_record_upload_path),
                ),
                (
                    "recording_type",
                    models.CharField(
                        choices=[("voice", "Voice"), ("video", "Video")],
                        default="voice",
                        max_length=10,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="accounts.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Latitude coordinate", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Longitude coordinate", max_digits=9
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(help_text="Location accuracy in meters"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Device timestamp of the location reading"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server timestamp of when the record was created",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="accounts.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="hourlyusage",
            constraint=models.CheckConstraint(
                check=models.Q(("hour__gte", 0), ("hour__lte", 23)),
                name="valid_hour_range",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.child",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="accounts.child",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="days",
            field=models.ManyToManyField(related_name="schedules", to="control.day"),
        ),
        migrations.AddField(
            model_name="userusage",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_usages",
                to="accounts.child",
            ),
        ),
        migrations.AddField(
            model_name="userusage",
            name="hourly_usages",
            field=models.ManyToManyField(
                related_name="child_usages", to="control.hourlyusage"
            ),
        ),
        migrations.AddIndex(
            model_name="childlocation",
            index=models.Index(
                fields=["child", "-timestamp"], name="control_chi_child_i_b7c3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childlocation",
            index=models.Index(
                fields=["-created_at"], name="control_chi_created_56e6c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userusage",
            unique_together={("child", "date")},
        ),
    ]
