# Generated by Django 5.0 on 2025-04-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_child_passkey"),
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Latitude coordinate", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Longitude coordinate", max_digits=9
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(help_text="Location accuracy in meters"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Device timestamp of the location reading"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server timestamp of when the record was created",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="accounts.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["child", "-timestamp"],
                        name="control_chi_child_i_b7c3df_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="control_chi_created_56e6c7_idx"
                    ),
                ],
            },
        ),
    ]
