# Generated by Django 5.0 on 2025-05-01 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_child_passkey"),
        ("control", "0003_notification_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChildBadWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bad_words", models.ManyToManyField(blank=True, to="control.badword")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_bad_words",
                        to="accounts.child",
                    ),
                ),
            ],
        ),
    ]
