# Generated by Django 5.0 on 2025-04-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_child_passlock"),
    ]

    operations = [
        migrations.CreateModel(
            name="HourlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.IntegerField()),
                ("usage_seconds", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["hour"],
            },
        ),
        migrations.CreateModel(
            name="UserUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="hourlyusage",
            constraint=models.CheckConstraint(
                check=models.Q(("hour__gte", 0), ("hour__lte", 23)),
                name="valid_hour_range",
            ),
        ),
        migrations.AddField(
            model_name="userusage",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_usages",
                to="accounts.child",
            ),
        ),
        migrations.AddField(
            model_name="userusage",
            name="hourly_usages",
            field=models.ManyToManyField(
                related_name="child_usages", to="control.hourlyusage"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userusage",
            unique_together={("child", "date")},
        ),
    ]
