# Generated by Django 5.0 on 2025-05-03 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0004_badword_childbadwords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="days_of_week",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="restriction_type",
        ),
        migrations.AddField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=1,
                help_text="Day of the week (0=Monday, 6=Sunday)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
            preserve_default=False,
        ),
    ]
