# Generated by Django 5.0 on 2025-05-03 00:12

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0005_remove_schedule_days_of_week_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="day_of_week",
        ),
        migrations.AddField(
            model_name="schedule",
            name="days_of_week",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday"),
                    ],
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(6),
                    ],
                ),
                default=1,
                help_text="List of days (0=Monday, ..., 6=Sunday)",
                size=None,
            ),
            preserve_default=False,
        ),
    ]
