# Generated by Django 5.0 on 2025-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0008_remove_schedule_days_delete_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="days",
            field=models.ManyToManyField(related_name="schedules", to="control.day"),
        ),
    ]
