# Generated by Django 5.0 on 2025-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0009_day_schedule_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="childlocation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
