# Generated by Django 5.0 on 2025-05-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_family_qr_image"),
        ("control", "0010_childlocation_is_deleted_notification_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildCallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="records/<django.db.models.fields.related.ForeignKey>"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="accounts.child",
                    ),
                ),
            ],
        ),
    ]
