# Generated by Django 5.0 on 2025-05-14 18:01

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0011_childcallrecording"),
    ]

    operations = [
        migrations.AddField(
            model_name="childcallrecording",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="childcallrecording",
            name="recording_type",
            field=models.CharField(
                choices=[("voice", "Voice"), ("video", "Video")],
                default="voice",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="childcallrecording",
            name="audio_file",
            field=models.FileField(upload_to=control.models.child_record_upload_path),
        ),
    ]
