# Generated by Django 5.0 on 2025-05-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0012_childcallrecording_is_read_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childcallrecording",
            old_name="audio_file",
            new_name="record_file",
        ),
    ]
